# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daily Fives
email: dailyfivesdotcom@gmail.com
description: Daily Fives is a blog that features five best articles from the web every day on various topics like technology, social media, productivity, life hacks, marketing and related things. It runs on Jekyll and is hosted on Github Pages. It is maintained by Ramkarthik.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dailyfives.com" # the base hostname & protocol for your site
twitter_username: Daily_Fives
github_username:  DailyFives

# Build settings
markdown: kramdown
permalink: "/:title"